PRODUCT_ID := a3004d
CLASS_ID:=iptime

CPU_NAME:=mt7621
WIFI_2G:=mt7602
WIFI_5G:=mt7612e
DRAM_SIZE:=128m

EXTERNAL_SWITCH:=y
HW_NAT:=y
FLASH_SIZE:=0x400000
KERNEL_SIZE:=0x180000
DRAM_SIZE_POSTFIX:=128m
EEPROM_FILE:=EEPROM_2G_FROM_2.1_SAMPLE.BIN
EEPROM_FILE_5G:=EEPROM_5G_FROM_2.1_SAMPLE.BIN
BOOT_FILENAME:=uboot.bin.$(DRAM_SIZE_POSTFIX).dual.1200MHz
USE_FACTORY_SECTION:=y
LOAD_ADDRESS := 80001000
LANG_PACKS:=kr,en

PRODUCT_TAG:=$(CPU_NAME).$(WIFI_2G).$(WIFI_5G).$(DRAM_SIZE)$(if $(OPTION_TAG),.$(OPTION_TAG))
KERNEL_FILENAME:=vmlinux.$(PRODUCT_TAG)
KCONFIG_FILE_NAME:=config.$(PRODUCT_TAG)
MODULE_DIR:=$(PRODUCT_TAG)

SDK_VERSION:=SDK_4300
KERNEL_PATH:=../../linux

